BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Osoba CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Zamestnanec CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Spolocnost CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Typ_Spolocnosti CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Typ_Vozna CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Vyradeny_Vozen CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Kontrola_Zamestnanec CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Vozen CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Kontrola CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Typ_Kontroly CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Vozen_Stanica CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Oprava CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Typ_Opravy CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Oprava_Suciastka CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Stanica CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Suciastka CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Typ_Suciastky CASCADE CONSTRAINTS';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -942
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_HISTORIA_CENY';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -4043
  THEN
    RAISE;
  END IF;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_REC_HISTORIA_CENY';
  EXCEPTION
  WHEN OTHERS THEN
  IF SQLCODE != -4043
  THEN
    RAISE;
  END IF;
END;